/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaminas;

import clases.Acciones;
import java.awt.GridLayout;
import javax.swing.JButton;


/**
 *
 * @author jacqueline
 */
public class VtnPrincipal extends javax.swing.JFrame {

    private int filas = 8;
    private int columnas = 8;
    private int minas = 6;
    private JButton[][] matrizBotones;
    private int [][] matrizLogica;
    
    /**
     * Creates new form VtnPrincipal
     */
    public VtnPrincipal() {
        initComponents();
        panelBotones.setLayout(new GridLayout (filas, columnas));
        inicializarMatrices();
        crearMinas();
        metodoInundacion();
    }

    public void inicializarMatrices(){
        matrizLogica = new int [filas][columnas];
        matrizBotones = new JButton[filas][columnas];
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                matrizBotones[i][j] = new JButton();
                panelBotones.add(matrizBotones[i][j]);
                matrizBotones[i][j].addActionListener(new Acciones(matrizLogica,matrizBotones,minas,filas,columnas,i, j));
            }
        }
    }
    
    public void crearMinas(){
        int aux = 0;
        while (aux < minas) {
            int fila = (int)(Math.random() * filas);
            int columna = (int)(Math.random() * columnas);
            if (matrizLogica[fila][columna] != -1) {
                matrizLogica[fila][columna] = -1;
                aux++;
                System.out.println("fila: " + (fila+1));
                System.out.println("columna: " + (columna+1));
            }
        }
    }
    
    public void metodoInundacion(){
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                if (matrizLogica[i][j] != -1) {
                    int minasAlrededor = 0;
                    if (i > 0 && j > 0 && matrizLogica[i-1][j-1] == -1) minasAlrededor++;
                    if (i > 0 && matrizLogica[i-1][j] == -1) minasAlrededor++;
                    if (i > 0 && j < columnas-1 && matrizLogica[i-1][j+1] == -1) minasAlrededor++;
                    if (j > 0 && matrizLogica[i][j-1] == -1) minasAlrededor++;
                    if (j < columnas-1 && matrizLogica[i][j+1] == -1) minasAlrededor++;
                    if (i < filas-1 && j > 0 && matrizLogica[i+1][j-1] == -1) minasAlrededor++;
                    if (i < filas-1 && matrizLogica[i+1][j] == -1) minasAlrededor++;
                    if (i < filas-1 && j < columnas-1 && matrizLogica[i+1][j+1] == -1) minasAlrededor++;
                    matrizLogica[i][j] = minasAlrededor;
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        tituloBuscaminas = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 241, 247));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotones.setBackground(new java.awt.Color(241, 252, 255));
        panelBotones.setPreferredSize(new java.awt.Dimension(395, 395));

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        fondo.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        tituloBuscaminas.setFont(new java.awt.Font("Silom", 0, 36)); // NOI18N
        tituloBuscaminas.setText("B U S C A M I N A S");
        fondo.add(tituloBuscaminas, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 26, -1, -1));

        btnReiniciar.setBackground(new java.awt.Color(0, 0, 0));
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar.setText("REINICIAR");
        btnReiniciar.setToolTipText("");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        fondo.add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JLabel tituloBuscaminas;
    // End of variables declaration//GEN-END:variables
}
